import "../styles/flag-icons-main/flag-icons-main/css/flag-icons.css";

export const Data = [
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-ke"></i>, " Kenya"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-br"></i>, " Brazil"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-us"></i>, " USA"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-za"></i>, " S. Africa"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-eg"></i>, " Egypt"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-tz"></i>, " Tanzania"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-au"></i>, " Australia"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-rs"></i>, " Russia"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-rw"></i>, " Rwanda"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-jm"></i>, " Jamaica"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-ht"></i>, " Haitti"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
  {
    pos: Math.ceil(Math.random() * 10),
    team: [<i className="fi fi-fj"></i>, " Fiji"],
    mp: Math.floor(Math.random() * 100),
    w: Math.floor(Math.random() * 100),
    d: Math.floor(Math.random() * 100),
    l: Math.floor(Math.random() * 100),
    pct: Math.floor(Math.random() * 100),
    pts: Math.floor(Math.random() * 100),
  },
];
